name: Terraform Validation

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/terraform-validation.yml'

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform Format
        run: terraform fmt -recursive -check ./
